In [1]:
import numpy as np
import statistics as stats
import pandas as pd

In [2]:
                # mean#
# with numpy
data = [50,70,40,60,90]
mean_value = np.mean(data)
mean_value

np.float64(62.0)

In [3]:
# with stats
mean = stats.mean(data)
mean

62

In [4]:
                       # median #
# with numpy
data1 = [51,45,101,36,28,8,0]
median_value = np.median(data1)
median_value

np.float64(36.0)

In [5]:
# with stats
median = stats.median(data1)
median

36

In [6]:
                      # mode #
# with stats
data2 = [3,4,2,1,3,2,4,3,4,1,3]
mode_value = stats.mode(data2)
mode_value

3

In [7]:
data3 = [5,1,9,9,5,2,5,2,1,5,2,9,2]
mode = stats.mode(data3)   # => we can use multimode() function
mode

5

In [8]:
''' Q1. in a math quiz ,there are scores of 11 students:
[45,25,48,52,60,58,52,49,55,60,63]
a) Find the mean of the scores.
b) find the median scores.
c) Find the mode of the scores '''

' Q1. in a math quiz ,there are scores of 11 students:\n[45,25,48,52,60,58,52,49,55,60,63]\na) Find the mean of the scores.\nb) find the median scores.\nc) Find the mode of the scores '

In [9]:
DATA = [45,52,48,52,60,58,52,49,55,60,63]

# mean
ans1 = stats.mean(DATA)
print(ans1)

# median
ans2 = stats.median(DATA)
print(ans2)

# mode
ans3 = stats.mode(DATA)
print(ans3)

54
52
52

In [10]:
# Measure of dispersion

In [11]:
population_data = {
    'Name':['Sameer','Praveen','Atksh','Bikash','Animesh'],
    'Age':[20,26,28,25,18],
    'Marks':[90,87,84,95,96]
}

df = pd.DataFrame(population_data)

In [12]:
df

      Name  Age  Marks
0   Sameer   20     90
1  Praveen   26     87
2    Atksh   28     84
3   Bikash   25     95
4  Animesh   18     96

In [ ]:
# i want to take out 3 rows as a sample
sample = df.sample(3, random_state=0) # random_state => to fix the pattern so everytime i get the same row
sample                                # we can write any value in random_state

      Name  Age  Marks
2    Atksh   28     84
0   Sameer   20     90
1  Praveen   26     87

In [17]:
# Range

data4 = [5,3,10,15,20,9,4,6,50,36,8]
   # range = max value - min value
range = max(data4)-min(data4)
range

47

In [18]:
# using numpy
np.ptp(data4)

np.int64(47)

In [19]:
# Variance

data5=[50,60,70,90,35]
np.var(data5)

np.float64(344.0)

In [20]:
# Standard Deviation

np.std(data5)

np.float64(18.547236990991408)